// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class product
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject productMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.product";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		price("price"),
		product_Category("MyFirstModule.product_Category"),
		product_tag("MyFirstModule.product_tag");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public product(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.product"));
	}

	protected product(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject productMendixObject)
	{
		if (productMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.product", productMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.product");

		this.productMendixObject = productMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'product.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.product initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.product.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.product initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.product(context, mendixObject);
	}

	public static myfirstmodule.proxies.product load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.product.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.product> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.product> result = new java.util.ArrayList<myfirstmodule.proxies.product>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.product" + xpathConstraint))
			result.add(myfirstmodule.proxies.product.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of price
	 */
	public final java.lang.Integer getprice()
	{
		return getprice(getContext());
	}

	/**
	 * @param context
	 * @return value of price
	 */
	public final java.lang.Integer getprice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.price.toString());
	}

	/**
	 * Set value of price
	 * @param price
	 */
	public final void setprice(java.lang.Integer price)
	{
		setprice(getContext(), price);
	}

	/**
	 * Set value of price
	 * @param context
	 * @param price
	 */
	public final void setprice(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer price)
	{
		getMendixObject().setValue(context, MemberNames.price.toString(), price);
	}

	/**
	 * @return value of product_Category
	 */
	public final myfirstmodule.proxies.Category getproduct_Category() throws com.mendix.core.CoreException
	{
		return getproduct_Category(getContext());
	}

	/**
	 * @param context
	 * @return value of product_Category
	 */
	public final myfirstmodule.proxies.Category getproduct_Category(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Category result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.product_Category.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Category.load(context, identifier);
		return result;
	}

	/**
	 * Set value of product_Category
	 * @param product_category
	 */
	public final void setproduct_Category(myfirstmodule.proxies.Category product_category)
	{
		setproduct_Category(getContext(), product_category);
	}

	/**
	 * Set value of product_Category
	 * @param context
	 * @param product_category
	 */
	public final void setproduct_Category(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Category product_category)
	{
		if (product_category == null)
			getMendixObject().setValue(context, MemberNames.product_Category.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.product_Category.toString(), product_category.getMendixObject().getId());
	}

	/**
	 * @return value of product_tag
	 */
	public final java.util.List<myfirstmodule.proxies.tag> getproduct_tag() throws com.mendix.core.CoreException
	{
		return getproduct_tag(getContext());
	}

	/**
	 * @param context
	 * @return value of product_tag
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.tag> getproduct_tag(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.tag> result = new java.util.ArrayList<myfirstmodule.proxies.tag>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.product_tag.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(myfirstmodule.proxies.tag.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of product_tag
	 * @param product_tag
	 */
	public final void setproduct_tag(java.util.List<myfirstmodule.proxies.tag> product_tag)
	{
		setproduct_tag(getContext(), product_tag);
	}

	/**
	 * Set value of product_tag
	 * @param context
	 * @param product_tag
	 */
	public final void setproduct_tag(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.tag> product_tag)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (myfirstmodule.proxies.tag proxyObject : product_tag)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.product_tag.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return productMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.product that = (myfirstmodule.proxies.product) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.product";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
